import { db, pool } from './index.ts';
import { registrySchema, systemSettings } from './schema.ts';
import { eq, asc, sql } from 'drizzle-orm';
import { INITIAL_REGISTRY_FORM_SCHEMA } from '../data/initialFormSchema.ts';
import { RegistryFormField, RegistryFormSchema } from '../types.ts';
import { toFieldKey } from '../utils/registryFieldUtils.ts';

export interface DbRegistryField {
  id: string;
  fieldKey: string;
  label: string;
  fieldType: string;
  required: boolean;
  visible: boolean;
  options?: any;
  fieldOrder: number;
  sectionId?: string | null;
  sectionTitle?: string | null;
  helpText?: string | null;
  placeholder?: string | null;
  defaultValue?: string | null;
  isFixed?: boolean | null;
  fixedValue?: string | null;
  isAutoGenerated?: boolean | null;
  autoGenType?: string | null;
  autoGenPattern?: string | null;
  autoGenPrefix?: string | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
}

/**
 * Retrieves all fields from the PostgreSQL registry_schema table, ordered by fieldOrder
 */
export async function getAllSchemaFieldsFromDb(): Promise<DbRegistryField[]> {
  try {
    const rows = await db
      .select()
      .from(registrySchema)
      .orderBy(asc(registrySchema.fieldOrder), asc(registrySchema.id));
    return rows as DbRegistryField[];
  } catch (err: any) {
    console.warn('Notice querying registry_schema table:', err.message);
    return [];
  }
}

/**
 * Retrieves a single field by ID from registry_schema
 */
export async function getSchemaFieldById(id: string): Promise<DbRegistryField | null> {
  try {
    const rows = await db
      .select()
      .from(registrySchema)
      .where(eq(registrySchema.id, id))
      .limit(1);
    return rows[0] as DbRegistryField || null;
  } catch (err: any) {
    console.warn('Notice querying field by id:', err.message);
    return null;
  }
}

/**
 * Upserts a field into the registry_schema table
 */
export async function upsertSchemaFieldInDb(field: Partial<DbRegistryField> & { id: string; label: string; fieldKey?: string }): Promise<DbRegistryField> {
  const fieldKey = field.fieldKey || toFieldKey(field.label, field.id);
  const record = {
    id: field.id,
    fieldKey,
    label: field.label,
    fieldType: field.fieldType || 'text',
    required: Boolean(field.required),
    visible: field.visible !== false,
    options: field.options || null,
    fieldOrder: field.fieldOrder ?? 0,
    sectionId: field.sectionId || 'sec_farm',
    sectionTitle: field.sectionTitle || null,
    helpText: field.helpText || null,
    placeholder: field.placeholder || null,
    defaultValue: field.defaultValue || null,
    isFixed: Boolean(field.isFixed),
    fixedValue: field.fixedValue || null,
    isAutoGenerated: Boolean(field.isAutoGenerated),
    autoGenType: field.autoGenType || null,
    autoGenPattern: field.autoGenPattern || null,
    autoGenPrefix: field.autoGenPrefix || null,
    updatedAt: new Date(),
  };

  const client = await pool.connect();
  try {
    const query = `
      INSERT INTO registry_schema (
        id, field_key, label, field_type, required, visible, options, field_order,
        section_id, section_title, help_text, placeholder, default_value,
        is_fixed, fixed_value, is_auto_generated, auto_gen_type, auto_gen_pattern, auto_gen_prefix,
        updated_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, NOW())
      ON CONFLICT (id) DO UPDATE SET
        field_key = EXCLUDED.field_key,
        label = EXCLUDED.label,
        field_type = EXCLUDED.field_type,
        required = EXCLUDED.required,
        visible = EXCLUDED.visible,
        options = EXCLUDED.options,
        field_order = EXCLUDED.field_order,
        section_id = EXCLUDED.section_id,
        section_title = EXCLUDED.section_title,
        help_text = EXCLUDED.help_text,
        placeholder = EXCLUDED.placeholder,
        default_value = EXCLUDED.default_value,
        is_fixed = EXCLUDED.is_fixed,
        fixed_value = EXCLUDED.fixed_value,
        is_auto_generated = EXCLUDED.is_auto_generated,
        auto_gen_type = EXCLUDED.auto_gen_type,
        auto_gen_pattern = EXCLUDED.auto_gen_pattern,
        auto_gen_prefix = EXCLUDED.auto_gen_prefix,
        updated_at = NOW()
      RETURNING *;
    `;
    const res = await client.query(query, [
      record.id,
      record.fieldKey,
      record.label,
      record.fieldType,
      record.required,
      record.visible,
      record.options ? JSON.stringify(record.options) : null,
      record.fieldOrder,
      record.sectionId,
      record.sectionTitle,
      record.helpText,
      record.placeholder,
      record.defaultValue,
      record.isFixed,
      record.fixedValue,
      record.isAutoGenerated,
      record.autoGenType,
      record.autoGenPattern,
      record.autoGenPrefix,
    ]);
    return res.rows[0] as DbRegistryField;
  } finally {
    client.release();
  }
}

/**
 * Deletes a field by ID from registry_schema
 */
export async function deleteSchemaFieldFromDb(id: string): Promise<boolean> {
  try {
    await db.update(registrySchema)
      .set({ visible: false, updatedAt: new Date() })
      .where(eq(registrySchema.id, id));
    return true;
  } catch (err: any) {
    console.warn('Notice deleting from registry_schema:', err.message);
    return false;
  }
}

/**
 * Synchronizes the entire RegistryFormSchema with the registry_schema table and system_settings
 */
export async function syncFullRegistrySchemaToDb(schema: RegistryFormSchema): Promise<RegistryFormSchema> {
  const published = {
    ...schema,
    isPublished: true,
    lastUpdated: new Date().toISOString(),
  };

  // 1. Save whole schema to system_settings for section hierarchy preservation
  try {
    const client = await pool.connect();
    try {
      await client.query(
        `INSERT INTO system_settings (key, value, updated_at)
         VALUES ($1, $2, NOW())
         ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();`,
        ['registry_form_schema', JSON.stringify(published)]
      );
    } finally {
      client.release();
    }
  } catch (err: any) {
    console.warn('Notice saving schema to system_settings:', err.message);
  }

  // 2. Upsert each field into registry_schema table
  try {
    const submittedFieldIds = new Set<string>();
    let orderCounter = 0;
    for (const section of schema.sections || []) {
      for (const field of section.fields || []) {
        orderCounter++;
        submittedFieldIds.add(field.id);
        await upsertSchemaFieldInDb({
          id: field.id,
          fieldKey: field.fieldKey || toFieldKey(field.label, field.id),
          label: field.label,
          fieldType: field.type,
          required: Boolean(field.required),
          visible: field.visible !== false,
          options: field.options,
          fieldOrder: orderCounter,
          sectionId: section.id,
          sectionTitle: section.title,
          helpText: field.helpText,
          placeholder: field.placeholder,
          defaultValue: field.defaultValue ? String(field.defaultValue) : null,
          isFixed: Boolean(field.isFixed),
          fixedValue: field.fixedValue,
          isAutoGenerated: Boolean(field.isAutoGenerated),
          autoGenType: field.autoGenType,
          autoGenPattern: field.autoGenPattern,
          autoGenPrefix: field.autoGenPrefix,
        });
      }
    }
    const existingFields = await getAllSchemaFieldsFromDb();
    const client = await pool.connect();
    try {
      for (const existingField of existingFields) {
        if (!submittedFieldIds.has(existingField.id)) {
          await client.query(
            'UPDATE registry_schema SET visible = FALSE, updated_at = NOW() WHERE id = $1',
            [existingField.id]
          );
        }
      }
    } finally {
      client.release();
    }
  } catch (err: any) {
    console.warn('Notice syncing individual fields to registry_schema:', err.message);
  }

  return published;
}

/**
 * Loads the complete schema, merging sections with rows from registry_schema table
 */
export async function getFullRegistrySchemaFromDb(): Promise<RegistryFormSchema> {
  let baseSchema: RegistryFormSchema = INITIAL_REGISTRY_FORM_SCHEMA;

  // 1. Try reading stored schema from system_settings
  try {
    const client = await pool.connect();
    try {
      const res = await client.query(`SELECT value FROM system_settings WHERE key = 'registry_form_schema' LIMIT 1`);
      if (res.rows.length > 0 && res.rows[0].value) {
        const val = typeof res.rows[0].value === 'string' ? JSON.parse(res.rows[0].value) : res.rows[0].value;
        if (val && Array.isArray(val.sections) && val.sections.length > 0) {
          baseSchema = val;
        }
      }
    } finally {
      client.release();
    }
  } catch {
    // fallback to initial
  }

  // 2. Fetch individual fields from registry_schema table to ensure live database synchronization
  try {
    const dbFields = await getAllSchemaFieldsFromDb();
    if (dbFields.length > 0) {
      // Index dbFields by id
      const dbFieldMap = new Map<string, DbRegistryField>();
      for (const df of dbFields) {
        dbFieldMap.set(df.id, df);
      }

      // Update existing fields in sections
      const updatedSections = baseSchema.sections.map(sec => ({
        ...sec,
        fields: sec.fields.map(f => {
          const df = dbFieldMap.get(f.id);
          if (df) {
            dbFieldMap.delete(f.id); // marked handled
            return {
              ...f,
              label: df.label,
              type: (df.fieldType as any) || f.type,
              required: Boolean(df.required),
              visible: df.visible !== false,
              options: df.options || f.options,
              fieldKey: df.fieldKey || f.fieldKey,
              helpText: df.helpText || f.helpText,
              placeholder: df.placeholder || f.placeholder,
            };
          }
          return f;
        }),
      }));

      // Append any newly added fields that were saved directly into registry_schema
      if (dbFieldMap.size > 0) {
        for (const [_, newDf] of dbFieldMap.entries()) {
          const targetSec = updatedSections.find(s => s.id === newDf.sectionId) || updatedSections[0];
          if (targetSec) {
            targetSec.fields.push({
              id: newDf.id,
              fieldKey: newDf.fieldKey,
              label: newDf.label,
              type: (newDf.fieldType as any) || 'text',
              required: Boolean(newDf.required),
              visible: newDf.visible !== false,
              options: newDf.options,
              helpText: newDf.helpText || undefined,
              placeholder: newDf.placeholder || undefined,
              defaultValue: newDf.defaultValue || undefined,
              isFixed: Boolean(newDf.isFixed),
              fixedValue: newDf.fixedValue || undefined,
              isAutoGenerated: Boolean(newDf.isAutoGenerated),
              autoGenType: (newDf.autoGenType as any) || undefined,
              autoGenPattern: newDf.autoGenPattern || undefined,
              autoGenPrefix: newDf.autoGenPrefix || undefined,
            });
          }
        }
      }

      baseSchema = {
        ...baseSchema,
        sections: updatedSections,
      };
    }
  } catch (err: any) {
    console.warn('Notice merging fields from registry_schema table:', err.message);
  }

  return baseSchema;
}
